batch_size: 128
maximum_epoch: 100

optimizer: Adam # [Adam, SGD]

# Adam setting
lr: 0.0001 
wd: 0.000001

# SGD sceduler setting
milestone:
- 50
- 75
- 90
warmup_epoch: 1


test_interval: 1
seed: 0

# dataset
dataset: decre_cifar100 # cifar10, cifar100, imagenet, decre_cifar100
root: /data/sung/dataset/cifar100 # lecun

# root: /data/sung/dataset/cifar10 # lecun cifar10
# root: /data/sung/dataset/imagenet # lecun imagenet

# decremental setting
random_order: True
num_class: 20


# log dir
log_dir: results # lecun