batch_size: 4
maximum_epoch: 1000

lr: 0.0001 
wd: 0.000001

test_interval: 1
seed: 0

# neptune
project: raeyo/decremental
token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI0OTA1Mzk4OS04MWI4LTQ5YjctYTViZi1iZDEyNjFlOWJmMzAifQ==

# dataset
dataset: cifar10 # cifar10, cifar100, imageNet
cifar: /data/dataset/cifar
imagenet: /data/dataset/imagenet

