
# model setting
model: resnet50_cifar100

pretrained: NULL # name of pretrained config

# training setting
batch_size: 128
maximum_epoch: 100
test_interval: 1
seed: 0

optimizer: SGD # [Adam, SGD]

# lr: 0.0001 # Adam
# wd: 0.000001 # Adam

# SGD sceduler setting
lr: 0.1
wd: 0.0005
milestone:
- 50
- 75
- 90
warmup_epoch: 1

# log dir
log_dir: /data2/raeyo/decremental/results # lecun, hinton

# dataset settings
dataset: cifar100 # cifar10, cifar100, imagenet, decre_cifar100

root: /data/sung/dataset/cifar100 # lecun
# root: /data/sung/dataset/cifar10 # lecun cifar10
# root: /data/sung/dataset/imagenet # lecun imagenet
# root: /data2/sung/dataset/imagenet # hinton imagenet

random_order: False
num_class: 100
