
# model and training setting
model: resnet50
pretrained: NULL

batch_size: 128
maximum_epoch: 100
test_interval: 1
seed: 2

optimizer: SGD # [Adam, SGD]

# # Adam setting
# lr: 0.0001 
# wd: 0.000001

# SGD sceduler setting
lr: 0.1
wd: 0.0005
milestone:
- 50
- 75
- 90
warmup_epoch: 1


# log dir
log_dir: results # lecun

#TODO: dataset settings
dataset: decre_cifar100 # cifar10, cifar100, imagenet, decre_cifar100
root: /data/sung/dataset/cifar100 # lecun
# root: /data/sung/dataset/cifar10 # lecun cifar10
# root: /data/sung/dataset/imagenet # lecun imagenet

# decremental setting
random_order: True
num_class: 20

