batch_size: 128
maximum_epoch: 100

lr: 0.0001 
wd: 0.000001
milestone:
- 50
- 75
- 90

test_interval: 1
seed: 0

# neptune
project: raeyo/decremental
token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI0OTA1Mzk4OS04MWI4LTQ5YjctYTViZi1iZDEyNjFlOWJmMzAifQ==

# dataset
dataset: cifar100 # cifar10, cifar100, imageNet
cifar: /data/sung/dataset/cifar100 # lecun
imagenet: /data/sung/dataset/imagenet # lecun

# log dir
log_dir: results # lecun