batch_size: 128
maximum_epoch: 100

optimizer: SGD # [Adam, SGD]

# Adam setting
lr: 0.0001 
wd: 0.000001
# SGD sceduler setting
milestone:
- 50
- 75
- 90
warmup_epoch: 1

test_interval: 1
seed: 0

# neptune
project: raeyo/decremental
token: eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI0OTA1Mzk4OS04MWI4LTQ5YjctYTViZi1iZDEyNjFlOWJmMzAifQ==

# dataset
dataset: dec_cifar # cifar10, cifar100, imageNet, dec_cifar
root: /data/sung/dataset/cifar100 # lecun
# root: /data/sung/dataset/cifar10 # lecun cifar10
# root: /data/sung/dataset/imagenet # lecun imagenet
# decremental setting
random_order: True
num_class: 20

# log dir
log_dir: results # lecun